# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeightGUI(object):
    def setupUi(self, WeightGUI):
        WeightGUI.setObjectName("WeightGUI")
        WeightGUI.resize(416, 300)
        self.centralwidget = QtWidgets.QWidget(WeightGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.WeightList = QtWidgets.QListView(self.centralwidget)
        self.WeightList.setGeometry(QtCore.QRect(20, 40, 256, 171))
        self.WeightList.setObjectName("WeightList")
        self.WeightLabel = QtWidgets.QLabel(self.centralwidget)
        self.WeightLabel.setGeometry(QtCore.QRect(50, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.WeightLabel.setFont(font)
        self.WeightLabel.setObjectName("WeightLabel")
        self.ImportButton = QtWidgets.QPushButton(self.centralwidget)
        self.ImportButton.setGeometry(QtCore.QRect(280, 40, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.ImportButton.setFont(font)
        self.ImportButton.setObjectName("ImportButton")
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(280, 100, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setObjectName("UpdateButton")
        self.PlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotButton.setGeometry(QtCore.QRect(280, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.PlotButton.setFont(font)
        self.PlotButton.setObjectName("PlotButton")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(20, 220, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        WeightGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeightGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 22))
        self.menubar.setObjectName("menubar")
        WeightGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeightGUI)
        self.statusbar.setObjectName("statusbar")
        WeightGUI.setStatusBar(self.statusbar)

        self.retranslateUi(WeightGUI)
        QtCore.QMetaObject.connectSlotsByName(WeightGUI)

    def retranslateUi(self, WeightGUI):
        _translate = QtCore.QCoreApplication.translate
        WeightGUI.setWindowTitle(_translate("WeightGUI", "MainWindow"))
        self.WeightLabel.setText(_translate("WeightGUI", "Weight List"))
        self.ImportButton.setText(_translate("WeightGUI", "Import Data"))
        self.UpdateButton.setText(_translate("WeightGUI", "Update Data"))
        self.PlotButton.setText(_translate("WeightGUI", "Plot"))
        self.SaveButton.setText(_translate("WeightGUI", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeightGUI = QtWidgets.QMainWindow()
    ui = Ui_WeightGUI()
    ui.setupUi(WeightGUI)
    WeightGUI.show()
    sys.exit(app.exec_())
