# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Plotter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Plot(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(293, 254)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 20, 81, 241))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.WeightLabel = QtWidgets.QCheckBox(Dialog)
        self.WeightLabel.setGeometry(QtCore.QRect(40, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.WeightLabel.setFont(font)
        self.WeightLabel.setObjectName("WeightLabel")
        self.ChestLabel = QtWidgets.QCheckBox(Dialog)
        self.ChestLabel.setGeometry(QtCore.QRect(40, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.ChestLabel.setFont(font)
        self.ChestLabel.setObjectName("ChestLabel")
        self.BellyLabel = QtWidgets.QCheckBox(Dialog)
        self.BellyLabel.setGeometry(QtCore.QRect(40, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.BellyLabel.setFont(font)
        self.BellyLabel.setObjectName("BellyLabel")
        self.UnderLabel = QtWidgets.QCheckBox(Dialog)
        self.UnderLabel.setGeometry(QtCore.QRect(40, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.UnderLabel.setFont(font)
        self.UnderLabel.setObjectName("UnderLabel")
        self.LThighLabel = QtWidgets.QCheckBox(Dialog)
        self.LThighLabel.setGeometry(QtCore.QRect(40, 150, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.LThighLabel.setFont(font)
        self.LThighLabel.setObjectName("LThighLabel")
        self.LBicepLabel = QtWidgets.QCheckBox(Dialog)
        self.LBicepLabel.setGeometry(QtCore.QRect(40, 180, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.LBicepLabel.setFont(font)
        self.LBicepLabel.setObjectName("LBicepLabel")
        self.SugarLabel = QtWidgets.QCheckBox(Dialog)
        self.SugarLabel.setGeometry(QtCore.QRect(40, 210, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.SugarLabel.setFont(font)
        self.SugarLabel.setObjectName("SugarLabel")
        self.PlotButton = QtWidgets.QPushButton(Dialog)
        self.PlotButton.setGeometry(QtCore.QRect(160, 100, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.PlotButton.setFont(font)
        self.PlotButton.setObjectName("PlotButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.WeightLabel.setText(_translate("Dialog", "Weight"))
        self.ChestLabel.setText(_translate("Dialog", "Chest"))
        self.BellyLabel.setText(_translate("Dialog", "Belly"))
        self.UnderLabel.setText(_translate("Dialog", "Under"))
        self.LThighLabel.setText(_translate("Dialog", "Left Thigh"))
        self.LBicepLabel.setText(_translate("Dialog", "Left Bicep"))
        self.SugarLabel.setText(_translate("Dialog", "Blood Sugar"))
        self.PlotButton.setText(_translate("Dialog", "Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Plot()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
